### ISSUE TITLE
Doesn't work with headphones

### ISSUE THREAD

**Issue by qwertyuiopasd1113** [Fangal-Airbag/Gamepad-Volume-Changer#1]
If the plugin is enabled, and headphones are plugged in, audio is still played back through the speakers

**Comment by Fangal-Airbag** [comment]
Hi so I just tested this and yeah your right I'm sorry. Problem is there's only one clear solution I can think of (this would be done in the plugin not by the user haha) is to remove the patch altogether when headphones are plugged in. Problem with that would be you wouldn't be able to control the volume via the plugin when headphones are plugged in. Is that something you would want?

**Comment by Fangal-Airbag** [comment]
Hey, just wondering if you'd still like the aforementioned feature to be implemented or not? I'd like to close this issue eventually.

**Comment by qwertyuiopasd1113** [comment]
It would be nice to be implemented

**Comment by DolphinCube** [comment]
Heyo! So I'm just curious... Is there any updates on this? Sorry for butting in. I also want to use headphones at times.

**Comment by Fangal-Airbag** [comment]
Hey there! With the [latest release](https://github.com/Fangal-Airbag/Gamepad-Volume-Changer/releases/tag/v2.0), this issue should be resolved. Thank you all so much for reporting it!

**Comment by DolphinCube** [comment]
> Hey there! With the [latest release](https://github.com/Fangal-Airbag/Gamepad-Volume-Changer/releases/tag/v2.0), this issue should be resolved. Thank you all so much for reporting it!

this fixes so much! Thank you!
