### ISSUE TITLE
Slow FPS in games and Wii U menus

### ISSUE THREAD

**Issue by Knkaku** [Fangal-Airbag/Gamepad-Volume-Changer#2]
Hello!
When this plugin is set to true, the FPS (speed) of the game and the Wii U menu will decrease
Can this be improved?

**Comment by Fangal-Airbag** [comment]
Fixed: https://github.com/Fangal-Airbag/Gamepad-Volume-Changer/commit/1d1a1eba6be60cbd2fa9ba8a5258c1b914e56a3d
